language: node_js
node_js:
  - "14"
install:
  - npm install
script:
  - npm test
before_deploy:
  - rvm $(travis_internal_ruby) --fuzzy do ruby -S gem install faraday -v 1.8.0
deploy:
  provider: heroku
  skip-cleanup: true
  api_key: $HEROKU_TOKEN
  app: node-travis-app2
